document.addEventListener("DOMContentLoaded", () => {
  const $ = (id) => document.getElementById(id);
  const billInput=$("bill"),sizeInput=$("size"),calculateBtn=$("calculate"),annualEl=$("annual"),costEl=$("cost"),paybackEl=$("payback");
  const money=v=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(Math.round(v));
  const currencyLabel=billInput?.closest(".input-wrap")?.querySelector("span");
  if(currencyLabel)currencyLabel.textContent="$";
  if(billInput&&(!billInput.value||Number(billInput.value)>=10000))billInput.value="300";
  function calculate(){if(!billInput||!sizeInput||!annualEl||!costEl||!paybackEl)return;const bill=Math.max(0,Number(billInput.value)||0),size=Number(sizeInput.value),coverage={3:.45,5:.65,10:.85,15:.95}[size]||0,s=bill*12*coverage,c=size*3150,p=s>0?c/s:0;annualEl.textContent=money(s);costEl.textContent=money(c);paybackEl.textContent=p?p.toFixed(1)+" years":"—"}
  if(calculateBtn)calculateBtn.addEventListener("click",calculate);if(billInput)billInput.addEventListener("input",calculate);if(sizeInput)sizeInput.addEventListener("change",calculate);
  const year=$("year");if(year)year.textContent=new Date().getFullYear();
  const menuToggle=$("menuToggle"),siteMenu=$("siteMenu"),menuClose=$("menuClose"),menuOverlay=$("menuOverlay");
  function closeMenu(){if(!siteMenu)return;siteMenu.classList.remove("open");if(menuOverlay)menuOverlay.classList.remove("open");siteMenu.setAttribute("aria-hidden","true");if(menuToggle){menuToggle.setAttribute("aria-expanded","false");menuToggle.setAttribute("aria-label","Open website menu")}document.body.classList.remove("menu-open")}
  function openMenu(){if(!siteMenu)return;siteMenu.classList.add("open");if(menuOverlay)menuOverlay.classList.add("open");siteMenu.setAttribute("aria-hidden","false");if(menuToggle){menuToggle.setAttribute("aria-expanded","true");menuToggle.setAttribute("aria-label","Close website menu")}document.body.classList.add("menu-open")}
  closeMenu();if(menuToggle)menuToggle.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();siteMenu&&siteMenu.classList.contains("open")?closeMenu():openMenu()});if(menuClose)menuClose.addEventListener("click",e=>{e.preventDefault();closeMenu()});if(menuOverlay)menuOverlay.addEventListener("click",closeMenu);if(siteMenu)siteMenu.querySelectorAll("a").forEach(link=>link.addEventListener("click",closeMenu));
  const searchToggle=$("searchToggle"),searchPanel=$("searchPanel"),siteSearch=$("siteSearch"),searchClear=$("searchClear"),searchStatus=$("searchStatus"),menuSearch=$("menuSearch"),articleCards=[...document.querySelectorAll(".article-card")],emptySearch=$("emptySearch");
  function closeSearch(){if(!searchPanel)return;searchPanel.classList.remove("open");searchPanel.setAttribute("aria-hidden","true");if(searchToggle){searchToggle.setAttribute("aria-expanded","false");searchToggle.setAttribute("aria-label","Open search")}}
  function openSearch(){if(!searchPanel)return;searchPanel.classList.add("open");searchPanel.setAttribute("aria-hidden","false");if(searchToggle){searchToggle.setAttribute("aria-expanded","true");searchToggle.setAttribute("aria-label","Close search")}requestAnimationFrame(()=>siteSearch&&siteSearch.focus())}
  let filterFrame=0;function filterArticles(query){cancelAnimationFrame(filterFrame);filterFrame=requestAnimationFrame(()=>{const q=query.trim().toLowerCase();let shown=0;[...document.querySelectorAll(".article-card")].forEach(card=>{const text=((card.dataset.search||"")+" "+card.textContent).toLowerCase(),match=!q||text.includes(q);card.hidden=!match;if(match)shown++});if(emptySearch)emptySearch.hidden=shown!==0||!q;if(searchStatus)searchStatus.textContent=q?shown+" article"+(shown===1?"":"s")+" found.":"Search the latest solar guides and categories."})}
  if(searchToggle)searchToggle.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();searchPanel&&searchPanel.classList.contains("open")?closeSearch():openSearch()});if(siteSearch)siteSearch.addEventListener("input",e=>filterArticles(e.target.value));if(searchClear)searchClear.addEventListener("click",()=>{if(!siteSearch)return;siteSearch.value="";filterArticles("");siteSearch.focus()});if(menuSearch&&siteMenu)menuSearch.addEventListener("input",e=>{const q=e.target.value.trim().toLowerCase();siteMenu.querySelectorAll(".menu-section a").forEach(link=>link.hidden=!!q&&!link.textContent.toLowerCase().includes(q))});document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeMenu();closeSearch()}});window.addEventListener("pageshow",()=>{closeMenu();closeSearch()});
  const homeMain=document.querySelector("main#home"),heroSection=document.querySelector(".hero"),latestSection=document.querySelector("#latest");
  if(homeMain&&heroSection&&!document.querySelector("#inverter-hub-home")){const section=document.createElement("section");section.id="inverter-hub-home";section.className="section";section.innerHTML=`<div class="container"><div class="section-heading"><div><p class="eyebrow">INVERTER HUB</p><h2>Latest Solar Inverter Models</h2></div><p>Explore inverter specifications, current USA price references and detailed model pages.</p></div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:18px"><a href="/eg4-6000xp.html" style="text-decoration:none;color:inherit;border:1px solid #e5eae7;border-radius:18px;overflow:hidden;background:#fff;box-shadow:0 8px 28px rgba(20,35,29,.05)"><img src="EG4-6000XP-All-In-One-Off-Grid-Inverter-Front.webp" alt="EG4 6000XP All-In-One Off-Grid Inverter" loading="lazy" style="width:100%;height:190px;object-fit:contain;background:#f5f8f6;display:block"><div style="padding:20px"><span class="tag">EG4</span><h3>EG4 6000XP</h3><p>6kW · 48V · dual MPPT · up to 8kW PV input</p><strong style="color:#16834b">$1,449.99 USD reference</strong><p style="color:#16834b;font-weight:700">View model →</p></div></a><a href="/eg4-12000xp.html" style="text-decoration:none;color:inherit;border:1px solid #e5eae7;border-radius:18px;overflow:hidden;background:#fff;box-shadow:0 8px 28px rgba(20,35,29,.05)"><img src="EG4-12000XP-All-In-One-Off-Grid-Inverter-Open.webp" alt="EG4 12000XP V2 All-In-One Off-Grid Inverter" loading="lazy" style="width:100%;height:190px;object-fit:contain;background:#f5f8f6;display:block"><div style="padding:20px"><span class="tag">EG4</span><h3>EG4 12000XP V2</h3><p>12kW · 48V · dual MPPT · up to 24kW PV input</p><strong style="color:#16834b">$1,899.99 USD reference</strong><p style="color:#16834b;font-weight:700">View model →</p></div></a><a href="/eg4-12kpv.html" style="text-decoration:none;color:inherit;border:1px solid #e5eae7;border-radius:18px;overflow:hidden;background:#fff;box-shadow:0 8px 28px rgba(20,35,29,.05)"><img src="EG4-12kPV-All-In-One-Hybrid-Inverter-Right-Tilt.webp" alt="EG4 12kPV All-In-One Hybrid Inverter" loading="lazy" style="width:100%;height:190px;object-fit:contain;background:#f5f8f6;display:block"><div style="padding:20px"><span class="tag">EG4</span><h3>EG4 12kPV</h3><p>Hybrid · 8kW continuous output · 12kW solar input</p><strong style="color:#16834b">$2,949.99 USD reference</strong><p style="color:#16834b;font-weight:700">View model →</p></div></a></div><div style="margin-top:18px"><a class="primary-btn" href="/inverters.html">Open Full Inverter Hub →</a></div></div>`;heroSection.insertAdjacentElement("afterend",section)}
  const inverterCategory=$("inverters"),newsCategory=$("news"),batteryCategory=$("batteries"),guideCategory=$("guides");if(inverterCategory)inverterCategory.href="/inverters.html";if(newsCategory)newsCategory.href="/solar-news.html";if(batteryCategory)batteryCategory.href="/solar-batteries.html";if(guideCategory)guideCategory.href="/solar-inverter-guides.html";
  if(siteMenu){siteMenu.querySelectorAll('a[href="#inverters"]').forEach(link=>link.href="/inverters.html");siteMenu.querySelectorAll('a[href="#news"]').forEach(link=>link.href="/solar-news.html");siteMenu.querySelectorAll('a[href="#batteries"]').forEach(link=>link.href="/solar-batteries.html");siteMenu.querySelectorAll('a[href="#guides"]').forEach(link=>link.href="/solar-inverter-guides.html")}
  if(latestSection&&!document.querySelector("#aug29-solar-rate-card")){const card=document.createElement("article");card.className="article-card";card.id="aug29-solar-rate-card";card.dataset.search="solar panel price today August 29 2026 LONGi Canadian Solar JA Solar Inverex solar rate";card.innerHTML=`<img src="solarrate.png" alt="Solar panel prices today August 29 2026" loading="lazy"><div class="article-body"><span class="tag">Solar Panel Prices</span><h3>Solar Panel Prices Today: August 29, 2026</h3><p>Compare featured LONGi, Canadian Solar, JA Solar and Inverex reference rates and learn what affects solar panel pricing.</p><a href="/solar-panel-prices-august-29-2026.html">Read article →</a></div>`;const grid=latestSection.querySelector("#articleGrid");if(grid)grid.prepend(card)}
  if(latestSection&&!document.querySelector("#us-foreign-power-equipment-card")){const card=document.createElement("article");card.className="article-card";card.id="us-foreign-power-equipment-card";card.dataset.search="US bans foreign-made power equipment solar inverter battery 2026 grid security news";card.innerHTML=`<img src="1787974583367.png" alt="U.S. restrictions on certain foreign-made power equipment affecting solar inverters and batteries" loading="lazy"><div class="article-body"><span class="tag">U.S. Solar News</span><h3>U.S. Restricts Certain Foreign-Made Power Equipment</h3><p>What the August 26, 2026 executive order could mean for qualifying grid-connected solar inverters, battery storage and related equipment.</p><a href="/us-restricts-foreign-power-equipment-solar-inverters-batteries-2026.html">Read article →</a></div>`;const grid=latestSection.querySelector("#articleGrid");if(grid)grid.prepend(card)}
  calculate();
});
